before_install:
  - 'npm i -g firebase-tools'

language: node_js
node_js:
  - stable


script:
  - cd client
  - npm install
  - npm run build
  - cd ..
  - cd functions
  - npm install
  - npm run build

